### ISSUE TITLE
Code in the paper

### ISSUE THREAD

**Issue by han2021-ya** [Deathstr0ke1/An-Audio-Information-Hide-Program-Using-DWT-and-SVD#1]
Hello! My research direction is audio steganography. After reading the code you uploaded, I have some questions to discuss with you. In addition, I have an unkind request. Can you send the paper corresponding to the code to my email? My email is han202010358@163.com , I have encountered problems in this research direction. I really want to discuss it with you. My phone number is 13358841657. I look forward to your reply.
                                                                                                                                                                                      Sincere Han Meng

**Comment by Deathstr0ke1** [comment]
I have contacted you in Email, please check if you can recieve it. @han2021-ya

**Comment by han2021-ya** [comment]
I can receive it. Thank you and look forward to your reply.

**Comment by han2021-ya** [comment]
Hello, I can receive your message. Thank you for your reply and look forward to communicating with you.






Hello, I can receive your message. Thank you for your reply and look forward to communicating with you.













At 2021-09-22 10:45:18, "Deathstroke" ***@***.***> wrote:

I have contacted you in Email, please check if you can recieve it. @han2021-ya

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
